# This is a basic workflow to help you get started with Actions

name: Run Arxiv Papers Daily

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron:  "0 0/6 * * *"  #'*/60 * * * *'
env:

  GITHUB_USER_NAME: AliTheFox86
  GITHUB_USER_EMAIL: wangqian@nudt.edu.cn
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: update
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          #architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv
          pip install requests
          pip install pyyaml
          
      - name: Run daily arxiv 
        run: |
          python nerf_daily_arxiv.py
          
      - name: Push nerf_daily_arxiv.md
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Github Action Automatic Update NeRF Arxiv Papers"
          #files: README.md docs/nerf-arxiv-daily.json docs/nerf-arxiv-daily-web.json docs/index.md docs/nerf-arxiv-daily-wechat.json docs/wechat.md
          files: README.md nerf-arxiv-daily.json
          rebase: 'true'
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
